# Generated by Django 2.1.2 on 2018-10-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='user_id',
            new_name='user',
        ),
    ]
