# Generated by Django 2.1.2 on 2018-11-01 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20181025_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='is_default',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Minimal length for name is 2 symbols'), django.core.validators.RegexValidator('^[\\wА-Яа-я ]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Minimal length for name is 2 symbols'), django.core.validators.RegexValidator('^[\\wА-Яа-я ]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
